# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Stickers.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Stickers.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0eStickers.proto\"\x8a\x01\n\x04Pack\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x1c\n\x05\x63over\x18\x03 \x01(\x0b\x32\r.Pack.Sticker\x12\x1f\n\x08stickers\x18\x04 \x03(\x0b\x32\r.Pack.Sticker\x1a$\n\x07Sticker\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05\x65moji\x18\x02 \x01(\t'
)




_PACK_STICKER = _descriptor.Descriptor(
  name='Sticker',
  full_name='Pack.Sticker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Pack.Sticker.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='emoji', full_name='Pack.Sticker.emoji', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=157,
)

_PACK = _descriptor.Descriptor(
  name='Pack',
  full_name='Pack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='Pack.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='author', full_name='Pack.author', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cover', full_name='Pack.cover', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stickers', full_name='Pack.stickers', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PACK_STICKER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=157,
)

_PACK_STICKER.containing_type = _PACK
_PACK.fields_by_name['cover'].message_type = _PACK_STICKER
_PACK.fields_by_name['stickers'].message_type = _PACK_STICKER
DESCRIPTOR.message_types_by_name['Pack'] = _PACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pack = _reflection.GeneratedProtocolMessageType('Pack', (_message.Message,), {

  'Sticker' : _reflection.GeneratedProtocolMessageType('Sticker', (_message.Message,), {
    'DESCRIPTOR' : _PACK_STICKER,
    '__module__' : 'Stickers_pb2'
    # @@protoc_insertion_point(class_scope:Pack.Sticker)
    })
  ,
  'DESCRIPTOR' : _PACK,
  '__module__' : 'Stickers_pb2'
  # @@protoc_insertion_point(class_scope:Pack)
  })
_sym_db.RegisterMessage(Pack)
_sym_db.RegisterMessage(Pack.Sticker)


# @@protoc_insertion_point(module_scope)
