# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Stickers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0eStickers.proto"\x8a\x01\n\x04Pack\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x1c\n\x05\x63over\x18\x03 \x01(\x0b\x32\r.Pack.Sticker\x12\x1f\n\x08stickers\x18\x04 \x03(\x0b\x32\r.Pack.Sticker\x1a$\n\x07Sticker\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05\x65moji\x18\x02 \x01(\t'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "Stickers_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_PACK"]._serialized_start = 19
    _globals["_PACK"]._serialized_end = 157
    _globals["_PACK_STICKER"]._serialized_start = 121
    _globals["_PACK_STICKER"]._serialized_end = 157
# @@protoc_insertion_point(module_scope)
